export const SUGGESTION_MARKER = "[AGENT_SUGGESTION]";
export const WORKING_MARKER = "[AGENT_WORKING]";
export const TRACE_MARKER = "[AGENT_TRACE]";
export const HANDOFF_MARKER = "[AGENT_HANDOFF]";
export const NO_REPLY_MARKER = "[AGENT_NO_REPLY]";
export const CORRECTION_FEEDBACK_MARKER = "[AGENT_CORRECTION_FEEDBACK]";
